image:
  repository: kingdavid24/cba-devops-project
  tag: 8bf4515
  pullPolicy: IfNotPresent
service: 
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
