---

name: CBA Devops Project Pipeline

on:
  push:
    branches:
        - main    

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Build Docker Image
        run: | 
          docker build -t docker.io/kingdavid24/cba-devops-project:${{ env.SHORT_SHA }} .
      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push to Dockerhub
        run: |
          docker push docker.io/kingdavid24/cba-devops-project:${{ env.SHORT_SHA }} 
      - name: Configure Git Author 
        run: |
          git config  --local user.email "davidjinanwa24@gmail.com"
          git config  --local user.name "TheGreatGenius"
      - name: Update Helm Chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./cba-devops-project-time-printer/values.yaml
          git add ./cba-devops-project-time-printer/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push 